### ISSUE TITLE
Your first death and possession gives you Attrition II instead of Attrition I.

### ISSUE THREAD

**Issue by James103** [stormdirus2/Memento-Mori#10]
When you die and possess a mob in Requiem without Memento-Mori, you retain Attrition I for 20 minutes as usual, without your Attrition automatically incrementing to level II.

However, when you die and possess a mob in Requiem with Memento-Mori, because of the ways Memento-Mori changes how Attrition works, the following actually happens:
1. You die and gain a level of Attrition, bring you to Attrition I (20:00).
2. You possess a mob.
3. At this point, since you have exactly 24000 ticks of Attrition I, that puts you right at the maximum permitted Attrition duration. Since you move up in Attrition levels if you are exactly at the max Attrition duration if you start possession, you gain Attrition II for a single tick.

Instead, the following should happen if and **only if** `/gamerule mementomori:attritionGrowth` is false:
1. You die and gain a level of Attrition, bring you to Attrition I (20:00).
2. You possess a mob.
3. At this point, since you have exactly 24000 ticks of Attrition I, that puts you right at the maximum permitted Attrition duration. As you should only move up in Attrition levels if your Attrition duration **exceeds** (not meets or exceeds) the maximum, you should stay in Attrition I, at least until you take any amount of soul damage.

Modlist (MC 1.16.5):
```
Mods:
  [✔️] cloth-config-4.11.19-fabric
  [✔️] fabric-api-0.29.3+1.16
  [❌] mementomori-2.0.3+1.16.5-fabric.jar (disabled)
  [✔️] mementomori-2.2.0+1.16.5-fabric
  [✔️] modmenu-1.14.13+build.19
  [❌] requiem-1.4.4.jar (disabled)
  [❌] requiem-1.5.0.jar (disabled)
  [✔️] requiem-1.5.1
  [❌] requiem-pandemonium-1.4.4.jar (disabled)
  [❌] requiem-pandemonium-1.5.0.jar (disabled)
  [❌] requiem-pandemonium-1.5.1.jar (disabled)
```

**Comment by stormdirus2** [comment]
This is intentional, let me explain:

Due to Attrition creep, the attrition growth mechanic, attrition grows over time while in a host, even to the point of upgrading the amplitude of the effect.

Keep in mind Attrition doesn't grow like this while you are a soul.
Additionally it uses soul damage to handle the transition between levels of attrition. Meaning that attrition creep can kill you if you creep to IV from III.
In order to prevent instant death upon possessing something at Attrition III I manually coded it so that it gives the next level of the effect if its at maximum duration but for a single tick.

Aka this is working as intended. The only problem I could see is if people turn Attrition growth off, at which point the single tick effect might be wonky, I'll look into it.
