### ISSUE TITLE
New gamerule `mementomori:maxAttritionLevel` (with max health scaling)

### ISSUE THREAD

**Issue by James103** [stormdirus2/Memento-Mori#3]
Currently, the maximum Attrition level you can survive without being killed due to soul damage is level III, since reaching Attrition IV will kill you.

I would like to be able to change this value via a new gamerule `mementomori:maxAttritionLevel`. This gamerule, which defaults to a value of 3 (III), controls the maximum Attrition level that you can survive without being killed due to excessive soul damage. Reaching an Attrition level greater than this value will kill you by any means due to excessive soul damage.

As a bonus, the max health reduction due to Attrition should scale with the value of the `mementomori:maxAttritionLevel` gamerule. For example,
* If the gamerule's value is 0, then getting the Attrition status effect will instantly kill you.
* A value of 1 allows you to survive Attrition I with half your max health. Attrition II will kill you.
* A value of 2 allows you to survive Attrition I with 2/3 max HP, Attrition II with 1/3 max HP. Attrition III will kill you.
* A value of 3 allows you to survive Attrition I with 3/4 max HP, Attrition II with 1/2 max HP, and Attrition III with 1/4 max HP.
* A value of 5 would allow you to survive up to Attrition V, albeit with only 1/6 of your max health.
* In general, your max health is multiplied by `(X + 1 - A) / (X + 1)`, where X is the max Attrition level as specified by the gamerule, and A is your current Attrition level, or 0 if you currently don't have any Attrition.

**Comment by stormdirus2** [comment]
Currently the way Requiem is wired, you are only supposed to go up to IV. Plus the effect's icon resets back to that of Attrition I if it somehow goes higher. That would be weird.

So basically, the hard limit would be Attrition IV.

Also getting the Attrition effect does not cause the event in which you die, that is soul damage and Attrition creep (the attrition growth while possessing a mob).

Additionally,  since I made it so reaching or interacting with Attrition IV through soul damage or creep kills you then the default for the gamerule would be 4 (IV).

A compromise would look quite different from what you are suggesting here.

However, I find it to be interesting so I will add it when I have the time.

For the modification of the health modifier: I feel like making the gamerule also control the health modifier is kinda restrictive. I feel it's better if I simply made two independent gamerules; one to control the Attrition level at which soul damage kills you, and the other to control the modification of maximum health at said level.

So the new changes are:
1. Add a gamerule that controls the level at which soul damage and soul creep kill you.
2. Add a gamerule that controls Attrition's reduction in maximum health.
